# Generated by Django 2.2 on 2019-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentasionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Presentasion Name', max_length=255)),
            ],
            options={
                'verbose_name': 'PresentasionName',
            },
        ),
    ]
