# Generated by Django 2.2 on 2019-06-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_presentasionname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubheaderText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Subheader_text name', max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'SubheaderText',
                'verbose_name_plural': 'SubheaderTexts',
            },
        ),
    ]
