# Generated by Django 2.2 on 2019-06-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_subheadertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubheaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'SubheaderImage',
                'verbose_name_plural': 'SubheaderImages',
            },
        ),
    ]
