# Generated by Django 2.2 on 2019-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='subheadertext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
